name: Build Goldberg for macOS

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest
    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Install dependencies
      run: |
        brew install cmake sdl2 sdl2_net

    - name: Create build directory
      run: mkdir build

    - name: Configure with CMake
      run: cmake $GITHUB_WORKSPACE -DCMAKE_OSX_ARCHITECTURES="x86_64;arm64"
      working-directory: build

    - name: Build with make
      run: make -j$(sysctl -n hw.ncpu)
      working-directory: build

    - name: Upload compiled binaries
      uses: actions/upload-artifact@v4
      with:
        name: goldberg-macos
        path: build/
